/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spdvi.fitnesscasesnoves.gui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import spdvi.fitnesscasesnoves.dataAcces.DataAccess;
import spdvi.fitnesscasesnoves.dto.Exercici;
import spdvi.fitnesscasesnoves.logica.LogicaExercicisFrame;

/**
 *
 * @author Rulox
 */
public class ExercicisFrame extends javax.swing.JFrame {

    private static JFrame parentFrame;

    /**
     * Creates new form ExercicisFrame
     */
    public ExercicisFrame() {

        // CREAR BOTON QUE BORRE LOS EJERCICIOS QUE NO TENGAN INTENTOS
        // FALTA TERMINAR BOTON DE NUEVO EJERCICIO
        initComponents();
        this.setLocationRelativeTo(null);
        insertarExercicisAlJTable();
        setTitle("Exercicis");

        this.parentFrame = this;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Exercicis");

        jButton1.setText("Tornar enrera");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Crear nou exercici");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton3))
                        .addGap(41, 41, 41))))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PaginaPrincipal aa = new PaginaPrincipal();
        aa.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Abrir el JFrame "CrearExercici"
        CrearExercici2 crearExerciciFrame = new CrearExercici2(this); // Asume que CrearExercici es el nombre de tu JFrame
        crearExerciciFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Para cerrar solo esta ventana
        crearExerciciFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Verificar si se ha seleccionado una fila en jTable1
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow != -1) { // Si una fila está seleccionada
            // Obtener el ID y el nombre del usuario seleccionado
            String exerciciId = jTable1.getValueAt(selectedRow, 0).toString();

            // Crear el mensaje del modal
            String mensaje = "¿Estas segur de voler eliminar l'exercici amb ID " + exerciciId + " i els seus intents i review relacionats a ell?";

            // Mostrar el modal de confirmación
            int respuesta = JOptionPane.showConfirmDialog(parentFrame, mensaje, "Confirmar eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            // Verificar la respuesta del usuario
            if (respuesta == JOptionPane.YES_OPTION) {
                // Lógica para eliminar el usuario de la base de datos
                DataAccess da = new DataAccess();
                da.eliminarExercici(Integer.parseInt(exerciciId)); // Método que elimina el usuario

                // Actualizar la tabla después de eliminar
                //insertarExercicisAlJTable(); // Método para volver a cargar la tabla
                JOptionPane.showMessageDialog(parentFrame, "Exercici eliminat amb exit."); // Mensaje de éxito
                insertarExercicisAlJTable();
            }
        } else {
            JOptionPane.showMessageDialog(parentFrame, "Selecciona un exercici per eliminar."); // Mensaje si no hay selección
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DataAccess da = new DataAccess();

// Obtener la fila seleccionada
        int selectedRow = jTable1.getSelectedRow();

// Verificar si una fila está seleccionada
        if (selectedRow != -1) {
            try {
                // Obtener los valores actuales de la fila seleccionada
                int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
                String nomExercici = jTable1.getValueAt(selectedRow, 1).toString();
                String descripcio = jTable1.getValueAt(selectedRow, 2).toString();

                // Mostrar un JOptionPane para editar el NomExercici
                String newNomExercici = JOptionPane.showInputDialog(this,
                        "Edita el Nom del Exercici", nomExercici);

                if (newNomExercici == null) {
                    return; // Salimos de la función si se cancela el primer diálogo
                }
                if (!newNomExercici.trim().isEmpty()) {
                    nomExercici = newNomExercici;
                }

                // Mostrar un JOptionPane para editar la Descripcio
                String newDescripcio = JOptionPane.showInputDialog(this,
                        "Edita la Descripció", descripcio);

                if (newDescripcio == null) {
                    return; // Salimos de la función si se cancela el segundo diálogo
                }
                if (!newDescripcio.trim().isEmpty()) {
                    descripcio = newDescripcio;
                }

                // Confirmar los cambios antes de guardar
                int respuesta = JOptionPane.showConfirmDialog(this,
                        "Estàs segur que vols modificar l'exercici amb id: " + id + "?",
                        "Confirmar modificació", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);

                if (respuesta == JOptionPane.YES_OPTION) {
                    // Crear el objeto Exercici con los nuevos datos
                    Exercici exercici = new Exercici(id, nomExercici, descripcio);

                    // Guardar el objeto Exercici en la base de datos
                    da.actualizarExercici(exercici);

                    JOptionPane.showMessageDialog(this, "Canvis desats correctament a la base de dades.");
                    insertarExercicisAlJTable();

                }
            } catch (NumberFormatException e) {
                System.out.println("Error al parsear les dades a la taula.");
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error: Alguns dades no son valides. Per favor, revisi la taula.");
            } catch (Exception e) {
                System.out.println("Error general al intentar editar el exercici.");
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila per editar.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    public final void insertarExercicisAlJTable() {
        LogicaExercicisFrame lef = new LogicaExercicisFrame(jLabel1, jTable1);
        lef.insertarExercicisAlJtext();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExercicisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExercicisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExercicisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExercicisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExercicisFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
