package spdvi.fitnesscasesnoves.gui;

import at.favre.lib.crypto.bcrypt.BCrypt;
import spdvi.fitnesscasesnoves.dto.Usuari;
import spdvi.fitnesscasesnoves.dataAcces.DataAccess;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rulox
 */
public class LogIn extends javax.swing.JFrame {
    
    // Variables para almacenar los valores de jTextPane1 y jPasswordField1
private String username; // Para almacenar el valor de jTextPane1
private String password; // Para almacenar el valor de jPasswordField1

   
    public LogIn() {
        initComponents();
        this.setLocationRelativeTo(null);// esto es para que se centre en la pantalla

        
        // Añadir FocusListener a jTextPane1 para capturar el valor cuando se pierda el foco
    jTextPaneUsuari.addFocusListener(new FocusAdapter() {
        @Override
        public void focusLost(FocusEvent e) {
            // Guardar el valor en la variable username cuando se pierda el foco
            username = jTextPaneUsuari.getText();
        
            
        }
    });
    
    // Añadir FocusListener a jPasswordField1 para capturar el valor cuando se pierda el foco
    jLabelTitolUsuari.addFocusListener(new FocusAdapter() {
        @Override
        public void focusLost(FocusEvent e) {
            // Guardar el valor en la variable password cuando se pierda el foco
            password = new String(jLabelTitolUsuari.getPassword()); // Convierte a String
            
            
            }
    });

    // Acción para el botón jButton1
   // jButton1.addActionListener(e -> validarUsuario());
}

// Método que valida el usuario contra la base de datos
private void validarUsuario() {
    // Llamar a la base de datos para verificar si el usuario existe
    DataAccess da = new DataAccess();
    Usuari user = da.getUsuarioByUsername(username); // Método que consulta el usuario por nombre

    // Verifica si el campo username está vacío
    if (username == null || username.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El campo de usuario no puede estar vacío.");
        return;
    }

    System.out.println("Usuario existe.");

    if (user != null) {
        // Comparar la contraseña ingresada con la contraseña de la base de datos
        if (BCrypt.verifyer().verify(password.toCharArray(), user.getPasswordHash()).verified) { // Usar BCrypt para validar la contraseña
            // Validar si el usuario es instructor
            if (user.isInstructor() == true) {
                // Si todo está bien, entra en el JFrame siguiente
                TerceraVentana terceraVentana = new TerceraVentana(); // instancia de la siguiente clase 'ventana'
                terceraVentana.setVisible(true);
                this.setVisible(false);
            } else {
                // Si no es instructor, mostrar mensaje de error
                JOptionPane.showMessageDialog(this, "No tiene acceso por no ser instructor.");
            }
        } else {
            // Si la contraseña no coincide, mostrar mensaje de error
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta.");
        }
    } else {
        // Si el usuario no existe, mostrar mensaje de error
        JOptionPane.showMessageDialog(this, "El usuario no existe.");
    }
}

    public Usuari getUsuarioByUsername(String username) {
    String sql = "SELECT * FROM usuaris WHERE Nom = ?";
    Usuari user = null;

    try (Connection connection = getConnection();
         PreparedStatement stmt = connection.prepareStatement(sql)) {
        
        stmt.setString(1, username); // Asignar el nombre de usuario al query
        ResultSet resultSet = stmt.executeQuery();

        if (resultSet.next()) {
            // Crear el objeto Usuario con los datos recuperados de la base de datos
            user = new Usuari(
                resultSet.getInt("Id"),
                resultSet.getString("Nom"),
                resultSet.getString("Email"),
                resultSet.getString("PasswordHash"),
                    
                // resultSet.getBytes("Foto"),
                resultSet.getBoolean("IsInstructor")
            );
        }
    } catch (SQLException ex) {
        Logger.getLogger(DataAccess.class.getName()).log(Level.SEVERE, null, ex);
    }

    return user;
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEntrarALaApp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneUsuari = new javax.swing.JTextPane();
        jLabelTitolUsuari = new javax.swing.JPasswordField();
        jLabelTitolLabel = new javax.swing.JLabel();
        jLabelTitolPassword = new javax.swing.JLabel();
        jLabelTitol = new javax.swing.JLabel();
        jButtonRegistre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonEntrarALaApp.setText("Entrar a la app");
        jButtonEntrarALaApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarALaAppActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPaneUsuari);

        jLabelTitolUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabelTitolUsuariActionPerformed(evt);
            }
        });

        jLabelTitolLabel.setText("Usuari");

        jLabelTitolPassword.setText("Contrasenya");

        jLabelTitol.setText("Registre d'usuaris");

        jButtonRegistre.setBackground(new java.awt.Color(242, 242, 242));
        jButtonRegistre.setText("Registra't");
        jButtonRegistre.setBorder(null);
        jButtonRegistre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabelTitol, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabelTitolPassword)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEntrarALaApp))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitolUsuari)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonRegistre)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(jLabelTitolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 114, Short.MAX_VALUE)))))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelTitol)
                .addGap(22, 22, 22)
                .addComponent(jLabelTitolLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTitolPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabelTitolUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButtonRegistre)
                .addGap(18, 18, 18)
                .addComponent(jButtonEntrarALaApp)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelTitolUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelTitolUsuariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelTitolUsuariActionPerformed

    private void jButtonEntrarALaAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarALaAppActionPerformed

        validarUsuario();
    }//GEN-LAST:event_jButtonEntrarALaAppActionPerformed

    private void jButtonRegistreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistreActionPerformed
        Register rgstr = new Register();
        rgstr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegistreActionPerformed
         /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrarALaApp;
    private javax.swing.JButton jButtonRegistre;
    private javax.swing.JLabel jLabelTitol;
    private javax.swing.JLabel jLabelTitolLabel;
    private javax.swing.JLabel jLabelTitolPassword;
    private javax.swing.JPasswordField jLabelTitolUsuari;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPaneUsuari;
    // End of variables declaration//GEN-END:variables

    private Connection getConnection() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
